# Generated by Django 5.2.6 on 2025-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='points_first',
        ),
        migrations.RemoveField(
            model_name='event',
            name='points_second',
        ),
        migrations.RemoveField(
            model_name='event',
            name='points_third',
        ),
        migrations.AlterField(
            model_name='result',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded by the judges.'),
        ),
    ]
