# Generated by Django 5.2.6 on 2025-09-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_points_first_remove_event_points_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
