# Generated by Django 5.2.6 on 2025-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_result_resultnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_general',
            field=models.BooleanField(default=False, help_text='Check if this event is for both Category A and B'),
        ),
    ]
