# Generated by Django 5.2.6 on 2025-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_event_category_remove_event_is_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
