# Generated by Django 5.2.6 on 2025-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_galleryimage_cloudinary_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description for the carousel image', max_length=255)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('cloudinary_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image should be shown in the carousel')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images appear (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
